[package]
name = "polkacard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schnorrkel = "0.10.2"
merlin = "3.0.0"
rand_core = "0.6.3"
